<?php
/**
* GS ProductContent
*
* @copyright Copyright (c) 2024 Gate-Software Sp. z o.o. (www.gate-software.com). All rights reserved.
* @author    Gate-Software Practice Team
* @author    sebastian.mazgaj@gate-software.com
*
* @package   GS ProductContent
*/
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 */
?>

<div class="product-info-price-custom-content">
    <p><?= $block->escapeHtml(__('Additional content under product price.')); ?></p>
</div>
